---
title: "`r title`"
author: "`r author`"
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    social: menu
    source_code: embed
    # theme: lumen
    storyboard: false
---

```{r packages}
# Load packages
library(pubDashboard)
library(dplyr)
library(ggflags)

```

```{r save_process_pubmed_batch, results='hide', eval=query_pubmed}
data <- fetch_openalex_pubs(journal_name = journal_name, 
                            journal_id = journal_id,
                            pages = 1, per_page = 1,
                            ...)
saveRDS(data, paste0(data_folder, "/data_new.rds"))

```

```{r continent_parent, child=c('continent.Rmd'), eval=tab_continent}
```

```{r continent_year_parent, child=c('continent_year.Rmd'), eval=tab_continent_year}
```

```{r continent_journal_parent, child=c('continent_journal.Rmd'), eval=tab_continent_journal}
```

```{r country_parent, child=c('country.Rmd'), eval=tab_country}
```

```{r country_journal_parent, child=c('country_journal.Rmd'), eval=tab_country_journal}
```

```{r psychology_parent, child=c('psychology.Rmd'), eval=tab_psychology}
```

```{r economics_parent, child=c('economics.Rmd'), eval=tab_economics}
```

```{r general_parent, child=c('general.Rmd'), eval=tab_general}
```

```{r figure1_parent, child=c('figure1.Rmd'), eval=tab_figure1}
```

```{r missing_parent, child=c('missing.Rmd'), eval=tab_missing}
```
