#' @title Generate a waffle plot made of country flags
#' @param data The processed dataframe of data
#' @param citation Optionally, a citation to add as a footer.
#' @param citation_size Font size of the citation.
#' @param data_formatted To save time, it is possible to reuse the dataframe
#' used for this function that is generated by [table_country()].
#' @examples
#' \dontrun{
#' data <- fetch_openalex_pubs(journal_name = "Collabra", pages = 1)
#' data <- clean_journals_continents(data)
#' waffle_country(data)
#' }
#' @importFrom rlang .data
#' @export
waffle_country <- function(data,
                           citation = NULL,
                           citation_size = NULL,
                           data_formatted = NULL) {
  insight::check_if_installed(c("ggflags", "ggplot2", "RColorBrewer"))
  layer <- ggplot2::layer

  if (is.null(data_formatted)) {
    x <- table_country(data, datatable = FALSE)
  } else if (inherits(data_formatted, "data.frame")) {
    x <- data_formatted
  } else if (inherits(data_formatted, "datatables")) {
    x <- data_formatted$x$data[-1]
  }

  x <- x %>%
    clean_top(8)

  colors <- suppressWarnings(RColorBrewer::brewer.pal(
    length(unique(x$continent)), "Set2"
  ))

  colours.country <- grDevices::colorRampPalette(colors)(length(x$Country))

  my_prop <- x %>%
    dplyr::mutate(
      Country = countrycode::countrycode(.data$Country,
                                         "country.name",
                                         "genc2c",
                                         # nomatch = NULL,
                                         # warn = FALSE
                                         ),
      Country = tolower(.data$Country)
    ) #%>%
    # dplyr::filter(!is.na(.data$Country))
  in_map_var <- lapply(seq_len(nrow(my_prop)), \(x) {
    rep(my_prop$Country[x], my_prop$Percentage[x])
  }) %>%
    unlist()

  p <- waffle_country_internal(in_map_var)

  if (!is.null(citation)) {
    p <- gg_citation(p, citation, citation_size = citation_size)
  }

  p
}

#' @noRd
waffle_country_internal <- function(in_map_var, len_x = NA, na_flag = NA) {
  . <- NULL
  my_prop <- in_map_var %>%
    data.frame(country = .) %>%
    dplyr::count(.data$country, sort = TRUE) %>%
    dplyr::arrange(is.na(.data$country))
    #%>%
    # dplyr::mutate(n2 = round(.data$n / nrow(in_map_var) * 100))
  # in_map_var <- lapply(seq_len(nrow(my_prop)), \(x) {
  #   rep(my_prop$country[x], my_prop$n[x])
  # }) %>%
  #   unlist()
  # work out grid dimensions
  # var_count <- length(in_map_var)
  # if (is.na(len_x)) {
  #   x_count <- ceiling(sqrt(var_count))
  # } else {
  #   x_count <- len_x
  # }
  # y_count <- ceiling(var_count / x_count)
  # y_count <- 10
  # grid_count <- x_count * y_count
  # df <-
  #   data.frame(
  #     x = rep(1:y_count, each = x_count),
  #     y = rep(1:x_count, y_count),
  #     country = c(in_map_var, rep(na_flag, grid_count - var_count))
  #   )
  df <- data.frame(
    x = rep(1:10, each = 10),
    y = rep(1:10, 10),
    country = c(in_map_var, rep(na_flag, 100 - length(in_map_var)))
  )
  # country_4legend <- unique(df$country)[unique(df$country) != na_flag]
  country_4legend <- c(unique(df$country)[!is.na(unique(df$country))]#, "Other"
                       )
  # country_4legend <- levels(df$country)
  country_4legend2 <- c(unique(df$country)[!is.na(unique(df$country))])

  country_4legend2 <- countrycode::countrycode(country_4legend2,
                                               "genc2c",
                                               "country.name")
  p <-
    ggplot2::ggplot(df, ggplot2::aes(.data$x, .data$y, country = .data$country)) +
    ggflags::geom_flag(size = 8.5) +
    ggflags::scale_country(
      labels = country_4legend2,
      breaks = country_4legend
                           ) +
    ggplot2::theme_void() +
    ggplot2::coord_equal() +
    ggplot2::theme(legend.title = ggplot2::element_blank()) +
    ggplot2::theme(legend.position = "right")
  # if (grid_count > var_count) {
  #   p <-
  #     p +
  #     ggplot2::geom_point(
  #       data = df[var_count:grid_count, ],
  #       ggplot2::aes(.data$x, .data$y), colour = "white", size = 10
  #     )
  # }
  p
}

